function characterGenerate () {

var firstNames= [
"Esthrev",
"Esther",
"Otti",
"Adounne",
"Abedinne",
"Dounia",
"Enegin",
"Ding ",
"Uwert ",
"Meincice",
"Iovan ",
"Oesgeese ",
"Loesse ",
"Wahler ",
"Menud ",
"Giselt ",
"Pawren ",
"Ellys ",
"Denys ",
"Orronomo ",
"Jhieng ",
"Direc ",
"Jiames ",
"Solomon ",
"Emilie ",
"Simone ",
"Giscard ",
"Dickery ",
"Opsley ",
"Peesmake ",
"Eppington ",
"Slater ",
"Marmery ",
"Lockdell ",
"Go-Whitting ",
"Chuckslee",
"Cooper ",
"Olivet ",
"Warde ",
"Deckart ",
"Peacher ",
"Elmswood",
"Fallada ",
"Giscert",
"Pickles",
"Morsley",
"Onlylle",
"Streder",
"Kade",
"Steke",
"Clere",
"Dorvey",
"Ann",
"Aura",
"Kimbo",
"Geggs",
"Maeter",
"Caesegyrt",
"Tyggs",
"Giesel",
"Derryn",
"Ilien",
"Verucia",
"Porto",
"Totian",
"Liovan",
"Merrys",
"Osmyn",
"Orhen",
"Oyzze",
"Juilliet",
"Silend",
"Dellys",
"Benet",
"Laszolo",
"Orenne",
"Limey",
"Lauret",
"Willon",
"Maisley",
"Porta",
"Teyen",
"Atillio",
"Sibilla",
"Giossa",
"Barbro",
"Ermolao",
"Boellielli",
"Detto",
"Magni",
"Corrado",
"Cecco",
"Aloian",
"Bardil",
"Croce",
"Drigo",
"Arrico",
"Dina",
"Evola",
"Garallo",
"Brunhi",
"Lussu",
"Gienna",
"Rhanca",
"Zaccaro",
"Ales",
"Zmitra",
"Zmito",
"Maksima",
"Vasil",
"Ciotko",
"Bykau",
"Barad",
"Ardulino",
"Kuzma",
"Uladz",
"Junko",
"Napaleo",
"Leu",
"Lew",
"Rhyn",
"Chanche",
"Lavazzi",
"Jaber",
"Fekyr",
"Taha",
"Tamakmul",
"Manrous",
"Ousmat",
"Toumats",
"Rifuan",
"Faruhi",
"Alit",
"Fauiz",
"Ahdat",
"Fandar",
"Chimo",
"Mohol",
"Jafiy",
"Gonles",
"Lipeng",
"Onjez",
"Inez",
"Kambul",
"Mapus",
"Rabad",
"Torsel",
"Tiers",
"Enwir",
"Woster",
"Owel",
"Eillion",
"Moship",
"Nisi",
"Derer",
"Garron",
"Mohd",
"Dhev",
"Radom",
"Ethmet",
"Mehmir",
"Miccal",
"Tipper",
"Suss",
"Liesse",
"Utto",
"Leon",
"Merrin",
"Clythe",
"Charlette",
"Yvette",
"Yves",
"Merie",
"Erienne",
"Leann",
"Joan",
"Florian",
"Egwind",
"Ten",
"Vieng",
"Wilhuff",
"Orchart",
"Phoebe",
"Anise",
"Birgit",
"Enger",
"Veera",
"Hanne",

];

var lastNames = [
"Tenderett",
"Botteng",
"Cardt",
"Clappard",
"Odding",
"Chand",
"Mudge",
"Smyde",
"Checkby",
"Sziler",
"Manhatte",
"Zaprude",
"Corsonne",
"Tesselmorn",
"Taschkend",
"Tacksmend",
"Haschkeer",
"Saranhada",
"Cassimentari",
"Bramavinder",
"Merrinderani",
"Morolentani",
"Stroodler",
"Dobier",
"Mayko",
"Kheirett",
"Abissenard",
"Cattabett",
"Castevets",
"Mitterance",
"Letherage",
"Tabbeyrand",
"Tarnymette",
"Manucort",
"Cortolaine",
"Kinnelauga",
"Laugesliega",
"Olaukine",
"Lemanute",
"Docking",
"Toal",
"ven Oppe",
"Compfnies",
"Pitmen",
"Lestersbeeg",
"ven Tochsgeen",
"Coombes",
"Ystmien",
"Cicemein",
"Giscert",
"Pickles",
"Borbierro",
"Feehlig",
"Sanne De",
"Selonylle",
"Condacie Dorvee",
"Ca Cha Rin",
"Penwilling",
"Markmercy",
"Jamesmede",
"Peakes",
"Morsman",
"Folferres",
"Enwyld",
"Do Tar",
"Fie",
"Donclere",
"Waterman",
"Foundler",
"Mawksweth",
"Chinchart",
"Hutchkiste",
"Kates",
"Toxse",
"Cordair",
"Bownstreet",
"Umberlee",
"Willson",
"Gardon",
"Stockside",
"Moffre",
"Bo",
"Leaswyte",
"Fearsmaeket",
"Maccoldand",
"Caron",
"Weedles",
"Susskee",
"Mecculf",
"Caelle",
"Seesgitty",
"Mossment",
"Fallado",
"Kerneski",
"Cziogdu",
"Mernold",
"Moellern",
"Daneer",
"Ecscil",
"Baratinxo",
"Jaczleeger",
"Vixhaies",
"Sedwig",
"Bordif",
"Muivesmant",
"Borbyel",
"Mandorin",
"Cechel",
"Maielsee",
"Macmou",
"Cetars",
"Viree",
"Calter",
"Gerstymine",
"Danderlee",
"Wingodling",
"Hannily",
"Onderstreet",
"Pudley",
"Gepperstring",
"Kiesluy",
"Zergodan",
"Borgedonn",
"Vantesuy",
"Mieuntro",
"Ghiers",
"Wokoman",
"Gianne",
"Kennent",
"Girillio",
"Costieri",
"Charpon",
"Tihats",
"Mosiallo",
"Pasteri",
"Eaudives",
"Garendier",
"Erboilli",
"Chutan",
"Guadirao",
"Mahsant",
"Sinnettre",
"Piers",
"Grinder",
"Joinnieri",
"Pertinderro",
"Blaster",
"Feltswick",
"Grozen",
"Gorozind",
"Furograzi",
"Cazrip",
"Niptari",
"Pozip",
"Wechslichter",
"Carogorin",
"Mortinbrandt",
"Fekry",
"Tanhan",
"Multmatak",
"Talind",
"Keldsmorton",
"Reeveswick",
"Smyde",
"Talley",
"Ompere",
"Millgan",
"Bakariz",
"Tomondoro",
"Po Da",
"Rheng",
"Jafiyan",
"Legson",
"Lo Zem",
"Ontezzo",
"Istant",
"Pumap",
"Darabad",
"Whygstone",
"Mep Bak",
"Cantsiegel",
"Toelley",
"Koenns",
"Hoggent",
"Listertree",
"Vogesmaine",
"Toopster",
"Wosterea",
"Berryat",
"Ysois",
"Millegant",
"Rocksmeet",
"Shiprom",
"Deveyn",
"Derer-Garron",
"Cabelle",
"Tiptoncel",
"Chankley",
"Yanglen",
"Chowleu",
"Yungfitt",
"Tonglim",
"Junne",
"Jhieng",
"Susskey",
"Morrimotto",
"Honder",
"Kowleu",
"Tarney",
"Kirshant",
"Bollew",
"Hounk",
"Meheph",
"Pethmer",
"Pashmeg",
"Tobrug",
"Golvizt",
"Urdont",
"Weltendrinkler",
"Baudenfiegel",
"Vogensmickert",
"Dorfeldtner",
"Gordonsteigel",
"Teigharber",
"Huistrickert",
"Oopdenforde",
"Poosforget",
"Doopsldinklert",
"Derstlieber",
"Osterling",
"Ammaneus",
"Estatagier",
"Doccies",
"Welwert",
"Pirzfigler",
"Loudender",
"Maseningen",
"Sieceldert",
"Housdessert",
"Carrager",
"Bessment",
"Beeseblest",
"Posterstickler",
"Trinksupper",
"Coragiere",
"Aviari",
"Porcono",
"Cobobliero",
"Murialiero",
"Porda",
"Partto",
"Tirpponen",
"Malamutti",
"Tifarenti",
"Falentinin",
"Quisling",
"Quickel",
"Querdette",
"Asquinne",
"Potash",
"Dulwaest",
"Hillies",
"De Wincee",
"Botton",
"Popette",
"Sopmaede",
"Covernes",
"Bortioli",
"De Yarre",
"Leigionne",
"Den Bort",
"Arndem",
"Daedlin",
"Everayde",
"Diecer",
"Den Doge",
"Easiyoe",
"Hader",
"Drander",
"Randern",
"Monbert",
"Cerdest",
"Esterhasling",
"Hesterbyden",
"Dayneeds",
"Puiglieri",
"Kitters",
"Poesy",
"Caetes",
"Ranger",
"Bertolt",
"Therdece",
"Miccals",
"Leec",
"Desgiers",
"Beedles",
"Lo Vangt",
"Duschiel",
"Dappier",
"Delligiori",
"Merryn",
"Cloth",
"Greene",
"Au Faebre",
"Dufitte",
"Betten",
"Winsomer",
"Dufelt",
"Hilliers",
"Oldwater",
"Doncastre",
"Penney",
"de Lancey",
"Egren",
"Orgryn",
"du March",
"Terries",
"Leemings",
"Doel",
"Greyfield",
"du Lienn",
"Heryott",
"Merrypitt",
"Kiehlring",
"Friels",
"Rackett",
"Chatham ",
"Tielig",
"Den Orr",
"Gamette",
"Heldeswaeter",
"Edgmint",
"Du Fours",
"Orcutt",
"Marchmont",
"Vance",
"Coberhae",
"Wahlens",
"Waalenaar",

];

var occupations = [
"architect",
"chandler",
"shipwright",
"clerk",
"magistrate",
"broker",
"weaver",
"carrier",
"carter",
"engineer",
"cleric",
"guard",
"messsenger",
"advocate",
"writ-carrier",
"speaker",
"herald",
"journalist",
"tanner",
"dyer",
"hawker",
"tinker",
"labourer",
"musician",
"assassin",
"cook",
"sailor",
"miner",
"housekeeper",
"domestic",
"servant",
"factory worker",
"investor",
"landowner",
"nobleperson",
"beadle",
"deacon",
"shopkeeper",
"fishmonger",
"slaughterperson",
"farmer",
"woodcutter",
"charcoal burner",
"customs agent",
"politician",
"iron monger",
"clock maker",
"paper maker",
"bookbinder",
"printer",
"brickmaker",
"potter",
"silverworker",
"wetnurse",
"doctor",
"glass-breaker",
"spiritualist",
"apothecary",
"barber",
"animalist",
"zoo-keeper",
"internist",
"speaker to ghosts",
"rogue",
"gigolo",
"sex-worker",
"radical",
"teacher",
"lecturer",
"childminder",
"sweetmaker",
"bacterist",
"charlatan",
"coffee roaster",
"brewer",
"winemaker",
"smokehouser",
"chancellor",
"clerk",
"auditor",
"dunghauler",
"costermonger",
"carpenter",
"thatcher",
"tiler",
"mosaic artist",
"vexatious litigant",
"water diviner",
"ganrdener",
"arborist",
"herbalist",
"cottager",
"crofter",
"sherpherd",
"bird catcher",
"angler",
"eel seller",
"temple guardian",
"sin eater",
"shaman",
"priest",
"incense grinder",
"spice taster",
"sommelier",
"assayer of gems and metals",
"taster",
"printer's assistant",
"copyist",
"editor",
"joiner",
"woodturner",
"nail cutter",
"smith",
"miller",
"grocer",
"draper",
"milliner",
"furrier",
"auctioneer",
"bookkeeper",
"gambling house keeper",
"tavern keeper",
"smuggler",
"vagabond",
"baker",
"pastry cook",
"bailiff",
"reeve at arms",
"watch keeper",
"place holder",
"landlord",
"hired thug",
"gunsmith",
"fletcher",
"armourer",
"cannon founder",
"foundry worker",
"coal-stoker",
"place-filler",
"dancer",
"beggar",
"gleaner",
"muck dragger",
"dredge trawler",
"lumber seller",
"basket weaver",
"censor",
"dog catcher",
"refuse collector",
"night soil carrier",
"midwife",
"nurse",
"lady's companion",
"gin steamer",
"druggist",
"drug house keeper",
"griddle cleaner",
"street sweeper",
"grass mower",
"dog trainer",
"circus worker",
"cog founder",
"carnival operator",
"sugarplum maker",
"book reviewer",
"crepe seller",
"florist",
"posy-seller",
"match-seller",
"ink-seller",
"pan-repairer",
"ostler",
"carriage repairer",
"groom",
"sandwich seller",
"advertiser",
"poster sticker",
"ice seller",
"prize fighter",
"knife sharpener",
"cobbler",
"spectacle maker",
"bellringer",
"housedresser",
"estate agent",
"chorister",
"ammanuensis",
"docent",
"fry cook",
"pork roaster",
"wheelwright",
"gravedigger",
"professional mourner",
"mason",
"clothes launderer",
"banker",
"beekeeper",
"aviarist",
"gosherd",
"swineherd",
"trinketeer",
"engraver",
"illustrator",
"muralist",
"juggler",
"sculptor",
"oil skimmer",
"wagoneer",
"maker of paper dolls",
"kite seller",
"doll maker",
"toy soldier founder",
"card shark",
"shell diver",
"tide picker",
"chartier",
"mapmaker",
"surveyor",
"flag embroiderer",
"paint seller",
"furniture seller",
"butler",
"valet",
"organ grinder",
"bear dancer",
"monkey trainer",
"vote faker",
"house steward",
"bowyer",
"cooper",
"soapmaker",
"storyteller",
"interpreter",
"translator",
"tout",
"fence",
"counterfeiter",
"mancatcher",
"bounty agent",
"astronomer",
"card oracle",
"salted piglet man",
"squid catcher",
"picture hanger",
"paper hanger",
"rat catcher",
"calendarist",
"calculator",
"dramatist",
"actor",
"lifeboat rower",
"barge puller",
"deckhand",
"dockhand",
"doctor's fetchling",
"water seller",
"tattooist",
"storyteller",
"puppet maker",
"puppetteer",
"street painter",
"chalk artist",
"diplomat",
"fortuner teller",
"palmist",
"distiller",
"masseuse",
"bone setter",
"consulting linguist",
"seal setter",
"seal carver",
"glazier",
"layabout",
"lounger",
"idler",
"scraper",
"bootbrush",
"coatchecker",
"wool brusher",
"yarn twister",
"loom setter",
"lens grinder",
"microscopist",
"bowel washer",
"vote-getter",
"doorman",
"archivist",
"librarian",
"house mover",
"bracefitter",
"corsetiere",
"lingeriere",
"lacemaker",
"crocheter",
"agronomist",
"hermit",
"reasoner",
"lighthouse keeper",
"lamplighter",
"tootchcaster",
"weatherwatcher",
"place-keeper",
"night cart puller",
"paid agitator",
"trinketeer",
]

var obsessions= [
"straightening old spoons",
"carrying grave earth in their pocket",
"keeping up with the laundry",
"the noise made by local dogs",
"the feel of well-kept leather",
"electromagnetism",
"storms, the properties of clouds, and the manner in which weather is formed",
"magic",
"what good nutritive attributes might be found in lichens",
"ways to cheat at cards",
"port wine",
"the trading tables and in particular the days price for a hundredweight of pine tar at each exchange",
"horse racing",
"collecting rubbish and keeping it in a sort of lean-to beside the privy",
"brushing their hair",
"diseases, their causes and symptoms",
"cleanliness, particularly the washing of their hands and face",
"saving money",
"clippping their nails",
"economising on boot polish",
"where parrots can be got for cheap",
"whether wild dogs roam the gardens and common grounds after dark",
"untested medicines",
"their health",
"whether they are getting enough sleep",
"saving money by reusing tobacco",
"dining at fine clubs and restaurants",
"pork, bacon, sweetbreads and other heavy foods",
"grinding their coffee very fine in a little pocket mill",
"ritual observance",
"toasted cheese",
"avoiding sunburn",
"whether other people can see their wrinkles",
"aged persons, and in particular the way their skin crinkles and folds",
"the shapes and images suggested by clouds",
"the formation of gems and stones by the action of tiny creatures living deep inside the earth",
"mirrors",
"childrens toys",
"windmills",
"plaster casts",
"wax",
"bodily fluids",
"wallpaper",
"rusted nails",
"finding a good place to get cheap ink",
"politics",
"celebrities",
"famous criminals",
"torn pieces of coloured paper found on the street",
"the bones of their hands and whether they appear wrong-sized to other people",
"shadows and sunlight",
"counting the days left in the season",
"preventing te rise of dark powers in the land",
"revanchist nationalism",
"the overthrow of religious authority",
"the overthrow of political authority",
"bettering their social position",
"becoming a noted storyteller",
"flies",
"spiders",
"the hair of cats, particularly the fine types which might be worked into yarn",
"various songs crowed by different roosters",
"the loudness or nearness of church bells",
"touching strangers' coats",
"the age of the world",
"whether there might be truth in the old legends",
"the doom they know to haunt their family",
"imagined slights",
"becoming a noted dandy",
"becoming a famous beauty",
"the arstocracy and their lifestyles",
"the ways of the poor and how they do get by on so little",
"new techniques of baking bread which take less time",
"cleaning their clothes using sunlight only",
"the possibility of powered flight",
"warfare and strategy",
"burnt pots",
"fingernail dirt",
"farts",
"the strength of various balloons",
"finding a lost treasure known only to a secret society to which they do not belong.",
"erotic art",
"going through their neighbours' rubbish",
"a potential pretender to the throne",
"holidaying in the mountains",
"walking under moonlight",
"fishing",
"trying every new chocolate offered by merchants in the town",
"tasting every type of fish in all the oceans of the world",
"finding the best way to erect a tent",
"keeping their trouser creases parallel",
"making a durable pair of paper shoes",
"chewing on dirt, which strengthens the constitution and moral fibre",
"spitting whenever they see a bird or a lamppost",
"eating twigs of various aromatc woods",
"tasting different tobaccos",
"finding the perfect pillow",
"the existence of particular undiscovered lands mentioned in religious texts",
"the location of fabled, lost cities",
"finding a passage through the leggio d'antiguey",
"picking and arranging wildflowers",
"catching grasshoppers",
"killing flies",
"chasing every mouse they see",
"chasing scraps of paper blown by the wind",
"famous judges and advocates",
"famous church figures",
"stealing from beggars' bowls",
"making cider",
"drinking more slowly than their fellows",
"their weight",
"whether they are going bald",
"whether they have had a hex put on them",
"finding rats in the storeroom",
"stealing from their neighbours",
"the notion that their neighbours are secretly watching them",
"learning how to do card tricks",
"recounting famous battles from the past",
"talking to strangers in public carriages",
"complaining to stewards about things beyond their control",
"whether the traffic is flowing well on the rivers",
"the rate of tax",
"the rate of excise",
"having pipe-smoking outlawed",
"the price of fish at market",
"the price of a hundredweight of barley on the exchanges",
"whether their neighbour secretly keeps geese in a partition of the common attic",
"the cleanliness of the streets",
"whether cattle and sheep owned by religious orders ought to be allowed to graze on common ground",
"making appeals to various courts to open up byways and paths which have been closed off by new building",
"harrassing the nightcart man about the timeliness of his attentions",
"ways to win at cards without appearing to cheat",
"writing letters to the editors of local journals on philosophical matters",
"petitioning the chancel to do something about didicot men",
"shouting at tinkers and street traders",
"disrupting street performances",
"teaching a pig to sing",
"seeing an injury to their pride revenged",
"overturning an unjust law that targets pedlars of pipe tobacco",
"collecting the lyrics of rare sailors jigs and ditties",
"ensuring the books on any shelf are just perfectly straight and in line with the edge",
"arranging small objects in lines or shapes",
"picking wildflowers and giving them to downcast or ailing persons",
"pressing insects and mounting them in little boxes",
"brewing a tasty pickle out of cabbages, quince and pear",
"recording every throw of the dice they ever make and trying to find patterns among them",
"developing a perfect historical system that will explain the rise and fall of the great powers of antiquity and predict future events",
"finding a way to have automata speak and make decisions",
"the perceived wastefulness of local bureaucracy",
"the perceived tendency of the local burghers and beadlerie towards censorship",
"whether people think they have smaller feet than is normal",
"whether one of their eyes is larger than the other",
"whether dogs can be made to understand human speech",
"whether cats can be made to sing in tune",
"whether mice have in them the capacity of reason",
"a curriculum for the perfect moral education of children",
"the possibility of a prophet being found who will reveal the folly of all established religion",
"whether there might truly be great and heavy calves with sweet meat and gentle temper who stroll about on the moon, eating sunbeams",
"whether it is poison to eat the green parts of a potato once it has been cooked",
"chasing ragabout children from the door of their house",
"harrassing the tellers of fortunes to get free readings of their future",
"knowing the horoscope of any person who they might meet",
"telling people their dreams and asking whether those dreams seem odd.",
"comparing the speed at which their hair grows to that other people",
"finding a way to patch their cuffs without it being obvious",
"how many persons a dog or a cat can recognise",
"a sure-fire plan for wealth creation they were told about in a tavern",
"a better way to get oil stains out of cloth garments",
"whether silkworms might be raced as can lice and dogs",
"whether turtles might make a placid and loyal pet",
"finding a better price for a brace of partridges than their neighbour",
"being the first of their fellows to have read the news paper",
"finding the playbills of pennyfright plays and cutting out the pictures to stick on their wall",
"being the first to hear the morning's news from the pieman",
]

// pick uses math.random*the length of the array, rounded down by math.floor, to specify a random index for an array. It then returns the value at that index.

function pick (list) {
var result=list[Math.floor(Math.random()*list.length)];
return result;
};

/*const pick = (list) => {
let result=list[Math.floor(Math.random()*list.length)]
return result	
}
*/

//the character object is built by running pick for each list of character attributes and assigning them to the object.

var character={
	firstName: pick(firstNames),
	lastName: pick(lastNames),
	occupation: pick(occupations),
	obsession: pick(obsessions),
	age: 16+Math.floor(Math.random()*70)
};

var characterAnswer= character.firstName+" "+character.lastName+ " is a "+character.occupation+". They are obsessed with "+character.obsession+", and they are " +character.age+" years old.";

document.getElementById("characterAnswer").innerHTML = characterAnswer;
}